version: '3.7'
services:
  db:
    container_name: fastapi-db
    image: postgres:latest
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - 5433:5432
    volumes:
      - usefulpgdata:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_db=postgres

  web:
    container_name: fastapi-web
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - ./:/app
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db
    command: poetry run uvicorn backend.main:app --host 0.0.0.0 --port 80 --reload
volumes:
  usefulpgdata: